import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'ar' | 'en';
  direction: 'rtl' | 'ltr';
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// قاموس الترجمة الكامل والشامل لجميع المكونات
const translations = {
  ar: {
    // --- المفاتيح الأساسية ---
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.services': 'الخدمات',
    'nav.countries': 'الدول',
    'nav.saudi': 'السعودية',
    'nav.uae': 'الإمارات',
    'nav.kuwait': 'الكويت',
    'nav.egypt': 'مصر',
    'nav.privacy': 'سياسة الخصوصية',
    'nav.terms': 'الشروط والأحكام',
    'hero.title': 'ابحث عن خدمات محلية',
    'hero.subtitle': 'في جميع أنحاء الشرق الأوسط',
    'hero.description': 'تواصل مع محترفين معتمدين في السعودية، الإمارات، الكويت، ومصر. احصل على عروض أسعار فورية وخدمة موثوقة لمنزلك وعملك.',
    'hero.call': 'اتصل الآن:',
    'hero.support': 'دعم 24/7',
    'hero.available247': 'متوفر 24/7',
    'about.title': 'عن LocalServices',
    'about.mission': 'مهمتنا',
    'contact.title': 'اتصل بنا',
    'services.title': 'جميع الخدمات',
    'services.description': 'تصفح جميع خدماتنا المتاحة في المنطقة.',
    'services.popular': 'خدمات شائعة',
    'services.availableInAllCountries': 'متوفر في جميع الدول',
    'terms.title': 'الشروط والأحكام',
    'privacy.title': 'سياسة الخصوصية',
    'notFound.title': 'الصفحة غير موجودة',
    'notFound.description': 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
    'button.viewServices': 'عرض الخدمات',
    'button.viewDetails': 'عرض التفاصيل',
    'button.bookNow': 'احجز الآن',
    'button.goBack': 'العودة',
    'button.goHome': 'الرئيسية',
    'button.contact': 'اتصل الآن',
    'button.submitRequest': 'إرسال طلب الخدمة',
    'language.toggle': 'EN',
    'city.servicesIn': 'الخدمات في',
    'city.reliableServices': 'خدمات موثوقة ومتاحة على مدار الساعة في',
    'city.availableServices': 'الخدمات المتاحة',
    'city.info': 'معلومات المدينة',
    'city.contact': 'معلومات التواصل',
    'city.region': 'المنطقة',
    'city.population': 'عدد السكان',
    'city.status': 'الحالة',
    'city.capital': 'العاصمة',
    'city.notFound': 'المدينة غير موجودة',
    'service.notFound': 'الخدمة غير متوفرة',
    'service.notAvailable': 'قد لا تكون الخدمة المطلوبة متوفرة في هذه المدينة، أو أن الرابط غير صحيح.',
    'service.checkURL': 'يرجى التحقق من الرابط أو الانتقال من صفحتنا الرئيسية.',
    'service.bestChoice': 'لماذا نحن الأفضل؟',
    'service.related': 'خدمات ذات صلة في',
    'service.features.certified': 'فنيون معتمدون ومؤهلون',
    'service.features.fast': 'خدمة سريعة في نفس اليوم',
    'service.features.warranty': 'ضمان على جميع الأعمال',
    'service.features.pricing': 'أسعار تنافسية وشفافة',
    'service.descriptionTitle': 'وصف الخدمة',
    'loading': 'جاري التحميل...',
    'whatsapp': 'واتساب',
    'emergency': 'طوارئ',
    'verified': 'موثق',
    'form.requestFor': 'طلب خدمة',
    'form.in': 'في',
    'form.fullName': 'الاسم الكامل',
    'form.phone': 'رقم الهاتف',
    'form.email': 'البريد الإلكتروني (اختياري)',
    'form.address': 'العنوان بالكامل',
    'form.problemDescription': 'صف المشكلة بالتفصيل...',
    'form.agreeToTerms': 'أوافق على شروط الخدمة وسياسة الخصوصية',
    'form.submitting': 'جاري الإرسال...',
    'startingFrom': 'يبدأ من',
    'pricing.onQuote': 'عند الطلب',
    'noServicesFound': 'لم يتم العثور على خدمات',
    'tryDifferentSearch': 'حاول تغيير معايير البحث',
    'allCategories': 'جميع الفئات',
    'allCountries': 'جميع الدول',
    'searchServices': 'ابحث عن خدمة...',
    'category.notFound': 'الفئة غير موجودة',
    'tabs.overview': 'نظرة عامة',
    'tabs.faq': 'الأسئلة الشائعة',
    'tabs.coverage': 'مناطق التغطية',
    'faq.none': 'لا توجد أسئلة شائعة لهذه الخدمة حاليًا.',
    'genericService.ctaTitle': 'هل تريد طلب هذه الخدمة؟',
    'genericService.ctaDescription': 'هذه الخدمة متاحة في العديد من المدن. اختر دولتك لعرض التفاصيل والأسعار المحلية.',
    'countries.availableIn': 'متوفر في 4 دول',
    'countries.explore': 'انقر لاستكشاف الخدمات',

    // --- مفاتيح جديدة تمت إضافتها ---
    'availability.realTime': 'التوفر في الوقت الفعلي',
    'availability.status.available': 'متوفر الآن',
    'availability.status.limited': 'توفر محدود',
    'availability.status.busy': 'مشغول - يوجد قائمة انتظار',
    'availability.responseTime': 'وقت الاستجابة',
    'availability.technicians': 'فنيون',
    'availability.available': 'متوفر',
    'availability.nextSlot': 'الموعد التالي المتاح:',
    'availability.emergency247': 'خدمة الطوارئ متاحة 24/7',
    'availability.lastUpdated': 'آخر تحديث:',
    'availability.today': 'اليوم',
    'availability.tomorrow': 'غداً',
    'availability.am': 'ص',
    'availability.pm': 'م',
    'footer.allRightsReserved': 'جميع الحقوق محفوظة',
    'footer.developerCredit': 'تصميم وبرمجة البيشو',
    'footer.majorCities': 'أهم المدن',
    'footer.popularServices': 'أشهر الخدمات',
    'footer.support': 'الدعم',
    'footer.contactUs': 'تواصل معنا',
    'emergency.title': 'خدمة طوارئ {serviceType}', // {serviceType} will be replaced dynamically
    'emergency.assistance.title': 'هل تحتاج مساعدة فورية؟',
    'emergency.assistance.description': 'فنيو الطوارئ لدينا على أهبة الاستعداد 24/7',
    'emergency.minResponse': 'استجابة خلال 15-30 دقيقة',
    'emergency.hotline': 'خط ساخن مباشر',
    'emergency.urgentRequest': 'طلب عاجل',
    'emergency.callHotline': 'اتصل بالخط الساخن للطوارئ',
    'emergency.description': 'للحالات العاجلة في السباكة، الكهرباء، أو التكييف - متوفر 24/7',
    'features.platform.title': 'لماذا تختار منصتنا',
    'features.platform.localExpertise.title': 'خبرة محلية',
    'features.platform.localExpertise.description': 'محترفون يفهمون منطقتك واحتياجاتك',
    'features.platform.instantConnection.title': 'تواصل فوري',
    'features.platform.instantConnection.description': 'تواصل مع محترفين محليين على الفور',
    'features.platform.verifiedProfessionals.title': 'محترفون موثوقون',
    'features.platform.verifiedProfessionals.description': 'يتم فحص جميع مزودي الخدمة والتحقق منهم بدقة',
    'contact.page.title': 'تواصل معنا',
    'contact.page.description': 'تواصل معنا للحصول على خدمات محلية موثوقة في جميع أنحاء الشرق الأوسط. نحن هنا للمساعدة 24/7.',
    'contact.phoneSupport': 'دعم هاتفي',
    'contact.instantResponse': 'استجابة فورية',
    'contact.professionalSupport': 'دعم احترافي',
    'about.page.title': 'عن LocalServices',
    'about.page.description': 'نحن المنصة الرائدة في الشرق الأوسط التي تربط العملاء بمزودي الخدمات المحليين الموثوقين. منذ عام 2020، نجعل الخدمات المنزلية والتجارية سهلة الوصول وموثوقة وبأسعار معقولة.',
    'about.mission.title': 'مهمتنا',
    'about.mission.text': 'تغيير طريقة وصول الناس إلى الخدمات المحلية من خلال إنشاء سوق موثوق وفعال وشفاف يفيد العملاء ومقدمي الخدمات في جميع أنحاء منطقة الشرق الأوسط.',
    'about.stats.happyCustomers': 'عميل سعيد',
    'about.stats.verifiedProfessionals': 'محترف موثوق',
    'about.stats.citiesCovered': 'مدينة مغطاة',
    'about.stats.averageRating': 'متوسط التقييم',
    'about.coverage.title': 'مناطق التغطية',
    'about.values.title': 'لماذا تختارنا؟',
    'about.values.trusted.title': 'شبكة موثوقة',
    'about.values.trusted.description': 'يخضع كل محترف في شبكتنا لعمليات فحص وتحقق صارمة لضمان جودة الخدمة.',
    'about.values.transparent.title': 'أسعار شفافة',
    'about.values.transparent.description': 'لا رسوم خفية، لا مفاجآت. احصل على أسعار واضحة وعروض أسعار مفصلة قبل بدء أي عمل.',
    'about.values.support.title': 'دعم 24/7',
    'about.values.support.description': 'فريق دعم العملاء لدينا متاح على مدار الساعة للمساعدة في أي أسئلة أو استفسارات.',
    'toast.requestSuccess.title': 'تم استلام طلبك بنجاح!',
    'toast.requestSuccess.description': 'سنتواصل معك في أقرب وقت ممكن.',
  },
  en: {
    // --- Basic Keys ---
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.services': 'Services',
    'nav.countries': 'Countries',
    'nav.saudi': 'Saudi Arabia',
    'nav.uae': 'UAE',
    'nav.kuwait': 'Kuwait',
    'nav.egypt': 'Egypt',
    'nav.privacy': 'Privacy Policy',
    'nav.terms': 'Terms & Conditions',
    'hero.title': 'Find Local Services',
    'hero.subtitle': 'Across the Middle East',
    'hero.description': 'Connect with verified local professionals in Saudi Arabia, UAE, Kuwait, and Egypt. Get instant quotes and reliable service for your home and business needs.',
    'hero.call': 'Call Now:',
    'hero.support': '24/7 Support',
    'hero.available247': '24/7 Available',
    'about.title': 'About LocalServices',
    'about.mission': 'Our Mission',
    'contact.title': 'Contact Us',
    'services.title': 'All Services',
    'services.description': 'Browse all our available services in the region.',
    'services.popular': 'Popular Services',
    'services.availableInAllCountries': 'Available in all countries',
    'terms.title': 'Terms & Conditions',
    'privacy.title': 'Privacy Policy',
    'notFound.title': 'Page Not Found',
    'notFound.description': "The page you're looking for doesn't exist or has been moved.",
    'button.viewServices': 'View Services',
    'button.viewDetails': 'View Details',
    'button.bookNow': 'Book Now',
    'button.goBack': 'Go Back',
    'button.goHome': 'Go Home',
    'button.contact': 'Call Now',
    'button.submitRequest': 'Submit Service Request',
    'language.toggle': 'عربي',
    'city.servicesIn': 'Services in',
    'city.reliableServices': 'Reliable services available 24/7 in',
    'city.availableServices': 'Available Services',
    'city.info': 'City Information',
    'city.contact': 'Contact Information',
    'city.region': 'Region',
    'city.population': 'Population',
    'city.status': 'Status',
    'city.capital': 'Capital',
    'city.notFound': 'City not found',
    'service.notFound': 'Service Not Available',
    'service.notAvailable': 'The requested service may not be available in this city, or the URL is incorrect.',
    'service.checkURL': 'Please check the URL or navigate from our homepage.',
    'service.bestChoice': 'Why Choose Us?',
    'service.related': 'Related Services in',
    'service.features.certified': 'Certified & Qualified Technicians',
    'service.features.fast': 'Fast, Same-Day Service',
    'service.features.warranty': 'Warranty on All Work',
    'service.features.pricing': 'Competitive & Transparent Pricing',
    'service.descriptionTitle': 'Service Description',
    'loading': 'Loading...',
    'whatsapp': 'WhatsApp',
    'emergency': 'Emergency',
    'verified': 'Verified',
    'form.requestFor': 'Request for',
    'form.in': 'in',
    'form.fullName': 'Full Name',
    'form.phone': 'Phone Number',
    'form.email': 'Email (Optional)',
    'form.address': 'Full Address',
    'form.problemDescription': 'Describe the problem in detail...',
    'form.agreeToTerms': 'I agree to the terms of service and privacy policy',
    'form.submitting': 'Submitting...',
    'startingFrom': 'Starting from',
    'pricing.onQuote': 'On Quote',
    'noServicesFound': 'No services found',
    'tryDifferentSearch': 'Try adjusting your search criteria',
    'allCategories': 'All Categories',
    'allCountries': 'All Countries',
    'searchServices': 'Search for a service...',
    'category.notFound': 'Category not found',
    'tabs.overview': 'Overview',
    'tabs.faq': 'FAQ',
    'tabs.coverage': 'Coverage Areas',
    'faq.none': 'No frequently asked questions for this service yet.',
    'genericService.ctaTitle': 'Want to book this service?',
    'genericService.ctaDescription': 'This service is available in multiple cities. Select your country to view local details and pricing.',
    'countries.availableIn': 'Available in 4 Countries',
    'countries.explore': 'Click to explore services',
    
    // --- New Keys Added ---
    'availability.realTime': 'Real-Time Availability',
    'availability.status.available': 'Available Now',
    'availability.status.limited': 'Limited Availability',
    'availability.status.busy': 'Busy - Queue Available',
    'availability.responseTime': 'Response Time',
    'availability.technicians': 'Technicians',
    'availability.available': 'Available',
    'availability.nextSlot': 'Next Available Slot:',
    'availability.emergency247': 'Emergency service available 24/7',
    'availability.lastUpdated': 'Last updated:',
    'availability.today': 'Today',
    'availability.tomorrow': 'Tomorrow',
    'availability.am': 'AM',
    'availability.pm': 'PM',
    'footer.allRightsReserved': 'All rights reserved',
    'footer.developerCredit': 'Designed & Developed by Elb3sho',
    'footer.majorCities': 'Major Cities',
    'footer.popularServices': 'Popular Services',
    'footer.support': 'Support',
    'footer.contactUs': 'Contact Us',
    'emergency.title': 'Emergency {serviceType} Service',
    'emergency.assistance.title': 'Need immediate assistance?',
    'emergency.assistance.description': 'Our emergency technicians are standing by 24/7',
    'emergency.minResponse': '15-30 min response',
    'emergency.hotline': 'Direct hotline',
    'emergency.urgentRequest': 'URGENT REQUEST',
    'emergency.callHotline': 'Call Emergency Hotline',
    'emergency.description': 'For urgent plumbing, electrical, or HVAC emergencies - Available 24/7',
    'features.platform.title': 'Why Choose Our Platform',
    'features.platform.localExpertise.title': 'Local Expertise',
    'features.platform.localExpertise.description': 'Professionals who understand your local area and needs',
    'features.platform.instantConnection.title': 'Instant Connection',
    'features.platform.instantConnection.description': 'Get connected with local professionals immediately',
    'features.platform.verifiedProfessionals.title': 'Verified Professionals',
    'features.platform.verifiedProfessionals.description': 'All service providers are thoroughly vetted and verified',
    'contact.page.title': 'Contact Us',
    'contact.page.description': "Get in touch with us for reliable local services across the Middle East. We're here to help 24/7.",
    'contact.phoneSupport': 'Phone Support',
    'contact.instantResponse': 'Instant Response',
    'contact.professionalSupport': 'Professional Support',
    'about.page.title': 'About LocalServices',
    'about.page.description': "We are the Middle East's leading platform connecting customers with trusted local service professionals. Since 2020, we've been making home and business services accessible, reliable, and affordable.",
    'about.mission.title': 'Our Mission',
    'about.mission.text': 'To transform how people access local services by creating a trusted, efficient, and transparent marketplace that benefits both customers and service professionals across the Middle East region.',
    'about.stats.happyCustomers': 'Happy Customers',
    'about.stats.verifiedProfessionals': 'Verified Professionals',
    'about.stats.citiesCovered': 'Cities Covered',
    'about.stats.averageRating': 'Average Rating',
    'about.coverage.title': 'Service Coverage',
    'about.values.title': 'Why Choose Us?',
    'about.values.trusted.title': 'Trusted Network',
    'about.values.trusted.description': 'Every professional in our network undergoes rigorous screening and verification processes to ensure quality service delivery.',
    'about.values.transparent.title': 'Transparent Pricing',
    'about.values.transparent.description': 'No hidden fees, no surprises. Get upfront pricing and detailed quotes before any work begins.',
    'about.values.support.title': '24/7 Support',
    'about.values.support.description': 'Our customer support team is available around the clock to assist with any questions or concerns.',
    'toast.requestSuccess.title': 'Your request has been received!',
    'toast.requestSuccess.description': 'We will contact you as soon as possible.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'ar' | 'en'>('ar');
  const direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.setAttribute('dir', direction);
    document.documentElement.setAttribute('lang', language);
  }, [language, direction]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (key: string): string => {
    const translation = (translations[language] as any)[key] || key;
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};